### PR TITLE
Update to 1.21.3

### PR DESCRIPTION
**Pull request by cputnam-a11y**
Please Update to 1.21.3

### CODE REVIEW

**Comment by Enecske** [comment]
Hello! Thanks for the PR!

I suppose you already tested the changes on 1.21.3. May I ask you to compile the new version into a jar file (with a sources jar), so I can upload it to Modrinth?

**Comment by vico93** [comment]
> Hello! Thanks for the PR!
> 
> I suppose you already tested the changes on 1.21.3. May I ask you to compile the new version into a jar file (with a sources jar), so I can upload it to Modrinth?

Can't speak for @cputnam-a11y, but i compiled it and tested in my modpack. The creepergriefing rule seems to be working correct (Creepers aren't exploding blocks when false). Didn't tested the other rules, though.

**Comment by cputnam-a11y** [comment]
> Hello! Thanks for the PR!
> 
> I suppose you already tested the changes on 1.21.3. May I ask you to compile the new version into a jar file (with a sources jar), so I can upload it to Modrinth?

I enabled actions on my fork, I will try to push today. I don't plan to provide a seperate jar, but you should be able to get it from actions

**Comment by cputnam-a11y** [comment]
The Build Artifacts can be found here:
  https://github.com/cputnam-a11y/MobExplosionGriefingGamerule/actions/runs/11577424235/artifacts/2118508524
I Plan To delete my branch should you merge it.

**Pull request merged**
